### ISSUE TITLE
Debug Modus von SH und Threading im Plugin

### ISSUE THREAD

**Issue by psilo909** [mworion/denon#1]
Hi,

ich habe aktuell das Problem, dass ich mit meinem Python 3.4 beim Abbruch mit STRG-C im Debugmodus von sh.py folgende Meldung - ausgelöst durch das Denon Plugin - kriege:

2016-04-02 09:10:33,227 INFO     Main         Thread: denon, still alive -- smarthome.py:stop:386
Exception ignored in: <module 'threading' from '/usr/local/python3/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/local/python3/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/usr/local/python3/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/volume1/python/smarthome/bin/smarthome.py", line 390, in stop
    exit()
  File "/usr/local/python3/lib/python3.4/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

Ich vermute, dass es Probleme mit dem Beenden des Threads für das Plugin gibt, muss aber selber nochmals genauer analysieren. Denke das hat irgendwie mit dem Lock zu tun, dass Du setzt.

**Comment by mworion** [comment]
OK, schaue ich mir auch mal an.

**Comment by psilo909** [comment]
Danke, ich schaue evtl auch tiefer rein.. Ich denke man sieht schon, dass es mit dem Lock zu tun hat:
File "/usr/local/python3/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
elif lock.acquire(block, timeout):

Vielleicht ist das Verhalten aber auch spezifisch bei meinem Denon.. Einfach mal versuchen nachzustellen..

**Comment by mworion** [comment]
Mit dem Denon ist so ein Problem. Meiner ist in den Antworten (Inhalt und Zeit) echt buggy. Zum Einen bekomme ich Timeouts, obwohl er angemeldet ist. Zum anderen hatte ich gesehen, dass er unter unterschiedlichen Lastbedingungen teilweise fehlerhafte Inhalte zurückliefert. Wahrscheinlich habe ich immer noch nicht alle Fehlerbedingungen abgefangen, die der Webserver im Denon erzeugt.

**Comment by psilo909** [comment]
Wenn ich mit meinem AVM Plugin mal komplett glücklich bin, kann ich gerne mal mit meinem 4200er durchtesten und auch überlegen, wo man stabiler machen kann.

**Comment by mworion** [comment]
you're welcome !

**Comment by mworion** [comment]
..ich bin mit dem Stand noch nicht sogzufrieden, um ihn in das zentrale Repo mit PR einzubringen...

**Comment by mworion** [comment]
Ich habe mich jetzt mal auf den Kern konzentriert, wo ich eigentlich einen lock haben muß, damit mehrere Anfragen sich nicht überschneiden. ->v0.55 auf Github.
Aber ganz ehrlich: als Hobbyprogrammierer fische ich da eher auch im Trüben....

**Comment by psilo909** [comment]
kein Problem, wie gesagt, wenn ich derzeit nicht am Neubau des AVM Plugins so aktiv wäre, hätte ich sowieso schon geschaut.. gleich mal die 0.55 testen..

**Comment by psilo909** [comment]
Sieht gut aus, Fehler ist erstmal weg!
